teethLab/Controllers/MoneyController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace teethLab.Controllers
{
    public class MoneyController : Controller
    {
        public ActionResult Export()
        {
            string _companyCheckBox = Request.Form["companyCheckBox"];
            string _companySelect = Request.Form["companySelect"];
            string _employeeSelect = Request.Form["employeeSelect"];
            string _employeeCheckBox = Request.Form["employeeCheckBox"];
            string _otherTo = Request.Form["otherTo"];
            string _otherCheckBox = Request.Form["otherCheckBox"];

            string _valueTo = Request.Form["valueTo"];
            string _toNotes = Request.Form["toNotes"];
            string _day = Request.Form["day"];

            teethLabEntities db = new teethLabEntities();
            if (_companyCheckBox == "on")
            {
                if (_companySelect != null && _companySelect != string.Empty)
                {
                    int companyId = int.Parse(_companySelect);
                    company comp = db.companies.FirstOrDefault(o => o.id == companyId);
                    if (comp != null)
                    {
                        int valueTo = int.Parse(_valueTo);
                        string toNotes = _toNotes;
                        if (_day != null)
                        {
                            DateTime date;
                            System.Globalization.CultureInfo enUS = new System.Globalization.CultureInfo("en-US");
                            DateTime.TryParseExact(_day, "yyyy-MM-dd", enUS,
                                                      System.Globalization.DateTimeStyles.None, out date);
                            if (date != null)
                            {

                                comp.credit--;
                                db.Entry(comp).State = System.Data.EntityState.Modified;
                                money money = new money { company = comp, currentCredit = comp.credit, import = false, notes = toNotes, value = valueTo, recieveDate = date };
                                db.moneys.Add(money);
                                db.SaveChanges();
                            }

                        }

                    }
                }
            }
            else if (_employeeCheckBox == "on")
            {
                int empId = int.Parse(_employeeSelect);
                employee emp = db.employees.FirstOrDefault(o => o.id == empId);
                if (emp != null)
                {
                    int valueTo = int.Parse(_valueTo);
                    string toNotes = _toNotes;
                    if (_day != null)
                    {
                        DateTime date;
                        System.Globalization.CultureInfo enUS = new System.Globalization.CultureInfo("en-US");
                        DateTime.TryParseExact(_day, "yyyy-MM-dd", enUS,
                                                  System.Globalization.DateTimeStyles.None, out date);
                        if (date != null)
                        {
                            emp.credit--;
                            db.Entry(emp).State = System.Data.EntityState.Modified;
                            money money = new money { employee = emp, currentCredit = emp.credit, import = false, notes = toNotes, value = valueTo, recieveDate = date };
                            db.moneys.Add(money);
                            db.SaveChanges();
                        }
                    }
                        
                }
            }
            else if (_otherCheckBox == "on")
            {
                string other = _otherTo;
             
                    int valueTo = int.Parse(_valueTo);
                    string toNotes = _toNotes;
                    if (_day != null)
                    {
                        DateTime date;
                        System.Globalization.CultureInfo enUS = new System.Globalization.CultureInfo("en-US");
                        DateTime.TryParseExact(_day, "yyyy-MM-dd", enUS,
                                                  System.Globalization.DateTimeStyles.None, out date);
                        if (date != null)
                        {

                            money money = new money { other = other, currentCredit = 0, import = false, notes = toNotes, value = valueTo, recieveDate = date };
                            db.moneys.Add(money);
                            db.SaveChanges();
                        }

                    }

            }

            return RedirectToAction("viewMoneyDays", new { day = _day });

        }
       
        public ActionResult Import()
        {
            string _doctorSelect = Request.Form["doctorSelect"];
            string _valueFrom = Request.Form["valueFrom"];
            string _fromNotes = Request.Form["fromNotes"];
  
            string _day = Request.Form["day"];

            teethLabEntities db = new teethLabEntities();

            if (_doctorSelect != null && _doctorSelect != string.Empty)
                {
                    int doctorId = int.Parse(_doctorSelect);
                    doctor doc = db.doctors.FirstOrDefault(o => o.id == doctorId);
                    if (doc != null)
                    {
                        int valueFrom = int.Parse(_valueFrom);
                        string fromNotes = _fromNotes;
                        if (_day != null)
                        {
                            DateTime date;
                            System.Globalization.CultureInfo enUS = new System.Globalization.CultureInfo("en-US");
                            DateTime.TryParseExact(_day, "yyyy-MM-dd", enUS,
                                                      System.Globalization.DateTimeStyles.None, out date);
                            if (date != null)
                            {
                                doc.Credit--;
                                db.Entry(doc).State = System.Data.EntityState.Modified;
                                money money = new money { doctor = doc, currentCredit = doc.Credit, import = true, notes = fromNotes, value = valueFrom, recieveDate = date ,payed=true};
                                db.moneys.Add(money);
                                db.SaveChanges();
                            }
                        }
                    }
                }
            
            return RedirectToAction("viewMoneyDays", new { day = _day });

        }
        public ActionResult delete() { 
        string _moneyId = Request.Form["moneyId"];
            if(_moneyId!=null&& _moneyId!=string.Empty ){
                int moneyId= int.Parse(_moneyId);
                teethLabEntities db = new teethLabEntities();
                money mon = db.moneys.FirstOrDefault(m=>m.id==moneyId);
                if(mon !=null){
                    if (mon.employee != null)
                    {
                        if (mon.import)
                        {
                            mon.employee.credit += mon.value;
                        }
                        else
                        {
                            mon.employee.credit -= mon.value;
                        }
                    }
                    else if (mon.doctor != null)
                    {
                        if (mon.import)
                        {
                            mon.doctor.Credit += mon.value;

                        }
                        else
                        {
                            mon.doctor.Credit -= mon.value;
                        }
                    }
                    else if (mon.company != null)
                    {
                        if (mon.import)
                        {
                            mon.company.credit += mon.value;
                        }
                        else
                        {
                            mon.company.credit -= mon.value;
                        }
                    }
                    db.Entry(mon).State = System.Data.EntityState.Deleted;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("viewMoneyDays", new { day = Request.Form["day"] });
        }
        public ActionResult viewMoneyDays()
        {
            teethLabEntities db = new teethLabEntities();
            //List<doctor> doctors = db.doctors.Where(d => d.isActive == true).ToList();
            //ViewData["doctors"] = doctors;
            //ViewData["emps"] = db.employees.ToList();
            //ViewData["companies"] = db.companies.ToList();

            //this.newDay();

            string day = Request.QueryString["day"];
            if (day != null)
            {
                DateTime date;
                System.Globalization.CultureInfo enUS = new System.Globalization.CultureInfo("en-US");
                DateTime.TryParseExact(day, "yyyy-MM-dd", enUS,
                                          System.Globalization.DateTimeStyles.None, out date);
                ViewData["day"] = date;
            }
            return View();
        }



    }
}

teethLab/Views/Money/Index.cshtml
@{
    ViewBag.Title = "المدفوعات";
}

<h2>المدفوعات</h2>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <label>اليوم</label>
            <input class="form-control" type="date" id="day" value="@DateTime.Now.ToString("yyyy-MM-dd")"/>
        <br />
        @{
            int credit = (int)ViewData["credit"];
        }
        <label>الرصيد</label><h1 id="credit">@credit</h1><!--<input class="form-control" type="text" id="credit" value="@credit" />-->
    </div>
</div>
<div class="row">
    <div class="col-md-offset-1 col-md-5">
        <h1>واردات</h1>
        <label>المبلغ</label><input type="text" id="cost" class="form-control" />
        <br />
        <label>دكتور</label>
        @{

            var doctors = (List<teethLab.doctor>)ViewData["doctors"];
        }
        <select id="doctor" class="form-control">
            <option value=""></option>
            @{
                foreach (teethLab.doctor doc in doctors)
                {
                    <option value="@doc.id">@doc.name</option>
                }
            }
        </select>
        <br />
        <input type="text" placeholder="المصدر" id="source" name="source" class="form-control"/>
        <br />
        <input type="button" id="import" value="اضافة" />
    </div>
    <div class="col-md-5">
        <h1>صادرات</h1>
        <label>المبلغ</label><input type="text" id="costEx" class="form-control" />
        <br />
        <label>موظف</label>
        @{

            var emps = (List<teethLab.employee>)ViewData["emps"];
        }
        <select id="emp" class="form-control">
            <option value="0"></option>
            @{
                foreach (teethLab.employee emp in emps)
                {
                    <option value="@emp.id">@emp.name</option>
                }
            }
        </select>
        <br />
        <label>شركة</label>
        @{

            var companies = (List<teethLab.company>)ViewData["companies"];
        }
        <select id="company" class="form-control">
            <option value="0"></option>

            @{
                foreach (teethLab.company comp in companies)
                {
                    <option value="@comp.id">@comp.name</option>
                }
            }
        </select>
        <br />
        <label>الصادر</label>
        <input type="text" id="productName" class="form-control" />
        <input type="button" id="export" value="اضافة" />
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#import").click(function () {
                cost = $("#cost").val();
                doctorId = $("#doctor").val();
                source = $("#source").val();
                day = $("#day").val();
                if (day == 0 || day == null || day == "") {
                    alert("يجب اختيار يوم");
                    return;
                }
                if (cost == "" || cost == null || isNaN(cost)) {
                    alert("يجب اضافة مبلغ");
                    return; 
                }

                if ((source == "" || source == null) && (doctorId == null || doctorId == "")) {
                    alert("يجب اختيار دكتور او كتابة مصدر");
                    return;
                }
                
                $.post('@Url.Action("import" , "Money")', "&cost=" + cost
                    + "&doctorId=" + doctorId
                    + "&source=" + source
                    + "&day=" + day
                    , function (res) {
                        if (res == "success") {
                            alert("تمت الاضافة");
                            window.location.href = "@Url.Action("Index", "Money")";
                        }
                    }
                    );
            });

            $("#export").click(function () {


                costEx = $("#costEx").val();
                empId = $("#emp").val();
                companyId = $("#company").val();
                productName = $("#productName").val();
                day = $("#day").val();
                if (day == 0 || day == null || day == "") {
                    alert("يجب اختيار يوم");
                    return;
                }

                if (costEx == "" || costEx == null || isNaN(costEx)) {
                    alert("يجب اضافة مبلغ");
                    return;
                }


                if ((productName == null || productName == "" || productName == 0)) {
                    alert("يجب كتابة مصدر");
                    return;
                }


                $.post('@Url.Action("export" , "Money")', "&cost=" + costEx
    + "&empId=" + empId
    + "&companyId=" + companyId
    + "&productName=" + productName
    + "&day=" + day
    , function (res) {
        if (res == "success") {
            alert("تمت الاضافة");

            window.location.href = "@Url.Action("Index", "Money")";
        }
    }
    );
            });

            $("#day").change(function () {
                $.post("@Url.Action("getDateCredit", "Money") ", "day=" + $(this).val(), function (res) {
                    if (res != null && res != "") {
                        $("#credit").html(res);
                    } else {
                        $("#credit").html(0);
                    }
                });
            });


        });

    </script>
}

teethLab/Views/Money/viewMoneyDays.cshtml
@{
    ViewBag.Title = "Money";


    DateTime day;
    if (ViewData["day"] == null)
    {
        day = DateTime.Now;
    }
    else
    {
        day = (DateTime)ViewData["day"];

    }

    //var moneyDay = (teethLab.moneyDay)ViewData["moneyDay"];

    teethLab.teethLabEntities db = new teethLab.teethLabEntities();
    //int lastId = db.moneyDays.Max(o => o.id);
    //int startCredit = 0;
    //if (lastId != 0)
    //{
    //    startCredit = db.moneyDays.Find(lastId).credit;
    //}

    //int credit = (int)ViewData["credit"];

    //var companies = (List<teethLab.company>)ViewData["companies"];

    //var emps = (List<teethLab.employee>)ViewData["emps"];

    //var doctors = (List<teethLab.doctor>)ViewData["doctors"];

    List<teethLab.money> moneyImport = db.moneys.Where(o => o.import == true && o.recieveDate.Value.Day == day.Day && o.recieveDate.Value.Month == day.Month && o.recieveDate.Value.Year == day.Year).ToList();
    List<teethLab.money> moneyExport = db.moneys.Where(o => o.import == false && o.recieveDate.Value.Day == day.Day && o.recieveDate.Value.Month == day.Month && o.recieveDate.Value.Year == day.Year).ToList();

}
<style>

</style>
<div>
    <div class="container">
        <div class="row headings">
        </div>
        <div class="row ">
            <div class="dateAndBalance">
                <input style="margin:10px auto !important" type="date" class="" value="@day.ToString("yyyy-MM-dd")" id="day" />
                <h2 style="margin:10px auto !important;width:20%">Starting Balance : <span id="startCredit">0</span></h2>
            </div>
        </div>
        <div class="row">
            <input type="button" id="toBtnToggle" value="to" style="width:100%" />
        </div>
        <div class="row" id="toDivToggle">
            <div class="alert-box ss-info hideit">
                <form class="alert-box ss-error hideit" method="post" action="@Url.Action("Export","Money")">


                    <div class="row">
                        <div class="col-md-4">
                            <select id="companySelect" name="companySelect" style="float:left" disabled>
                                <option>Companies</option>
                                @{
                                    foreach (var item in db.companies)
                                    {
                                        <option value="@item.id">@item.name</option>
                                    }
                                }
                            </select>
                            <input type="checkbox" name="companyCheckBox" style="float:left" id="companyCheckBox" />
                        </div>
                        <div class="col-md-4">
                            <label style="float:left"></label>

                            <select style="float:left" id="employeeSelect" name="employeeSelect" disabled>
                                <option>Employees</option>
                                @{
                                    foreach (var item in db.employees)
                                    {
                                        <option value="@item.id">@item.name</option>
                                    }
                                }
                            </select>
                            <input type="checkbox" style="float:left" name="employeeCheckBox" id="employeeCheckBox" />

                        </div>
                        <div class="col-md-4">


                            <input class="form-control" style="float:left" type="text" name="otherTo" id="otherTo" disabled placeholder="other" />
                            <input type="checkbox" style="float:left" id="otherCheckBox" name="otherCheckBox" />
                            <input type="hidden" class="" value="@day.ToString("yyyy-MM-dd")" name="day" />

                        </div>




                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <input class="form-control" type="number" id="valueTo" name="valueTo" placeholder="value" />

                        </div>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="toNotes" name="toNotes" placeholder="notes" />

                        </div>
                        <div class="col-md-4">
                            <input class="form-control" type="submit" id="toBtn" name="toBtn" value="Add" />

                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-md-3">To</div>
                    <div class="col-md-3">Value</div>
                    <div class="col-md-3">Notes</div>
                    <div class="col-md-3">
                    </div>
                </div>

                @{

                    int exportsum = 0;
                    foreach (teethLab.money money in moneyExport)
                    {
                        exportsum += money.value;
                        <div class="row">
                            @{
                        if (money.company != null)
                        {
                            <div class="col-md-3">@money.company.name</div>
                        }                       
                        else if (money.employee != null)
                        {
                            <div class="col-md-3">@money.employee.name</div>
                        }
                        else
                        {
                            <div class="col-md-3">@money.other</div>

                        }
}
                            <div class="col-md-3">@money.value</div>
                            <div class="col-md-3">@money.notes</div>
                            <div class="col-md-3">
                                <form method="post" action="@Url.Action("delete", "Money")">
                                    <input type="hidden" name="moneyId" value="@money.id" />
                                    <input type="hidden" class="" value="@day.ToString("yyyy-MM-dd")" name="day" />
                                    <input class="form-control" type="submit" id="deleteToBtn" value="Delete" />
                                </form>
                            </div>
                        </div>
                    }
                }
<div class="row">
    <h1>Sum : <span id="exportsum">@exportsum</span></h1>
</div>
            </div>

        </div>
        <div class="row">
            <input type="button" id="fromBtnToggle" value="from" style="width:100%" />
        </div>
        <div class="row" id="fromDivToggle">
            <div class="tables">
                <div class="alert-box ss-info hideit">
                    <form class="alert-box ss-error hideit" method="post" action="@Url.Action("Import","Money")">


                        <div class="row">
                            <div class="col-md-3">
                                <select id="doctorSelect" style="float:left">
                                    <option>Doctors</option>
                                    @{
                                        foreach (var item in db.doctors)
                                        {
                                            <option value="@item.id">@item.name</option>
                                        }
                                    }
                                </select>
                            </div>

                            <div class="col-md-3">
                                <input class="form-control" type="number" id="valueFrom" placeholder="value" />


                            </div>
                            <div class="col-md-3">
                                <input class="form-control" type="text" id="fromNotes" placeholder="notes" />

                            </div>
                            <input type="hidden" class="" value="@day.ToString("yyyy-MM-dd")" name="day" />

                            <div class="col-md-3">
                                <input class="form-control" type="submit" id="fromBtn" value="Add" />

                            </div>
                        </div>
                    </form>

                    <div class="row">
                        <div class="col-md-3">To</div>
                        <div class="col-md-3">Value</div>
                        <div class="col-md-3">Notes</div>
                        <div class="col-md-3">
                        </div>
                    </div>

                    @{

                        int importsum = 0;
                        foreach (teethLab.money money in moneyImport)
                        {
                            importsum += money.value;
                            <div class="row">
                                @{
                          if (money.doctor != null)
                            {
                                <div class="col-md-3">@money.doctor.name</div>
                            }
                     
                                }
                                <div class="col-md-3">@money.value</div>
                                <div class="col-md-3">@money.notes</div>
                                <div class="col-md-3">
                                    <form method="post" action="@Url.Action("delete", "Money")">
                                        <input type="hidden" class="" value="@day.ToString("yyyy-MM-dd")" name="day" />
                                        <input type="hidden" name="moneyId" value="@money.id" />
                                        <input class="form-control" type="submit" id="deleteFromBtn" value="Delete" />
                                     </form>
                                </div>
                            </div>
                        }
                    }
                    <div class="row">
                        <h1>Sum : <span id="exportsum">@importsum</span></h1>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="EndBalance">
                <h2>Ending Balance : <span id="currentCredit">0</span></h2>
            </div>

        </div>
    </div>

</div>


@section scripts{
    <script>
        $(document).ready(function () {


            $("#toBtnToggle").click(function () {
                $("#toDivToggle").slideToggle();
            });

            $("#fromBtnToggle").click(function () {
                $("#fromDivToggle").slideToggle();
            });
            $("#companyCheckBox").change(function () {
                if ($(this).is(":checked")) {
                    $("#companySelect").removeAttr("disabled");
                    $("#employeeSelect").attr("disabled", "")
                    $("#otherTo").attr("disabled", "")
                    $("#employeeCheckBox").removeAttr("checked")
                    $("#otherCheckBox").removeAttr("checked")

                } else {
                    $("#companySelect").attr("disabled", "")
                }
            });

            $("#employeeCheckBox").change(function () {
                if ($(this).is(":checked")) {
                    $("#employeeSelect").removeAttr("disabled");
                    $("#companySelect").attr("disabled", "")
                    $("#otherTo").attr("disabled", "")
                    $("#companyCheckBox").removeAttr("checked")
                    $("#otherCheckBox").removeAttr("checked")

                } else {
                    $("#employeeSelect").attr("disabled", "")
                }
            });


            $("#otherCheckBox").change(function () {
                if ($(this).is(":checked")) {
                    $("#otherTo").removeAttr("disabled");
                    $("#employeeSelect").attr("disabled", "")
                    $("#companySelect").attr("disabled", "")
                    $("#companyCheckBox").removeAttr("checked")
                    $("#employeeCheckBox").removeAttr("checked")
                } else {
                    $("#otherTo").attr("disabled", "")
                }
            });

            $("#day").change(function () {
                window.location.href = "/Money/viewMoneyDays?day=" + $("#day").val();
            });

        });

    </script>
}