teethLab/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace teethLab.Controllers
{
    public class DoctorController : Controller
    {
        private teethLabEntities db = new teethLabEntities();

        //
        // GET: /Doctor/

        public ActionResult Index()
        {
            return View(db.doctors.ToList());
        }


        public JsonResult all()
        {
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;

            int totalRows, page = 1, size, offset, numOfPages;
            if (Request.Params["page"] != null && Request.Params["page"] != "")
            {
                page = int.Parse(Request.Params["page"]);
            }
            page--;
            size = 5;
            offset = page * size;
            totalRows = db.doctors.Count();
            var models = db.doctors.OrderBy(o => o.id).Skip(offset).Take(size).ToList();
            numOfPages = totalRows / size;
            if (totalRows % size != 0)
            {
                numOfPages++;
            }


            return Json(new { models = models, numOfPages = numOfPages }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Add(doctor model)
        {
            if (ModelState.IsValid)
            {
                db.doctors.Add(model);
                db.SaveChanges();
                return Json(new { success = true, model = model });
            }
            else
            {
                var errors = getErrors(ModelState);
                var res = new { success = false, errors = errors };

                return Json(res);
            }
        }

        private Dictionary<string, List<string>> getErrors(ModelStateDictionary ModelState)
        {
            Dictionary<string, List<string>> errors = new Dictionary<string, List<string>>();
            foreach (var key in ModelState.Keys)
            {
                if (ModelState[key].Errors.Count > 0)
                {
                    List<string> keyErrors = new List<string>();
                    foreach (var error in ModelState[key].Errors)
                    {
                        keyErrors.Add(error.ErrorMessage);
                    }
                    errors.Add(key, keyErrors);
                }
            }
            return errors;
        }


        [HttpPost]
        public JsonResult Edit(doctor model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            else
            {
                var errors = getErrors(ModelState);
                var res = new { success = false, errors = errors };

                return Json(res);
            }
        }
        [HttpPost]
        public JsonResult Delete(doctor model)
        {
            doctor obj = db.doctors.Find(model.id);
            db.doctors.Remove(obj);
            db.SaveChanges();
            return Json(new { success = true });
        }
        public ActionResult DoctorProfile(int id)
        {
            doctor doc = db.doctors.FirstOrDefault(o => o.id == id);
            if (doc != null)
            {
                return View(doc);
            }
            return HttpNotFound();
        }

        ////
        //// GET: /Doctor/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    doctor doctor = db.doctors.Find(id);
        //    if (doctor == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(doctor);
        //}

        ////
        //// GET: /Doctor/Create

        //public ActionResult Create()
        //{
        //    return View();
        //}

        ////
        //// POST: /Doctor/Create

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(doctor doctor)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.doctors.Add(doctor);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(doctor);
        //}

        ////
        //// GET: /Doctor/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    doctor doctor = db.doctors.Find(id);
        //    if (doctor == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(doctor);
        //}

        ////
        //// POST: /Doctor/Edit/5

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(doctor doctor)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(doctor).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(doctor);
        //}

        ////
        //// GET: /Doctor/Delete/5

        //public ActionResult Delete(int id = 0)
        //{
        //    doctor doctor = db.doctors.Find(id);
        //    if (doctor == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(doctor);
        //}

        ////
        //// POST: /Doctor/Delete/5

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    doctor doctor = db.doctors.Find(id);
        //    db.doctors.Remove(doctor);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

teethLab/Controllers/caseDoctorPricesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace teethLab.Controllers
{
    public class caseDoctorPricesController : Controller
    {
        private teethLabEntities db = new teethLabEntities();

        //
        // GET: /caseDoctorPrices/

        public ActionResult Index()
        {
            var casedoctorprices = db.caseDoctorPrices.Include(c => c.CurrentCas).Include(c => c.doctor);
            return View(casedoctorprices.ToList());
        }

        //
        // GET: /caseDoctorPrices/Details/5

        public ActionResult Details(int id = 0)
        {
            caseDoctorPrice casedoctorprice = db.caseDoctorPrices.Find(id);
            if (casedoctorprice == null)
            {
                return HttpNotFound();
            }
            return View(casedoctorprice);
        }

        //
        // GET: /caseDoctorPrices/Create

        public ActionResult Create()
        {
            ViewBag.caseId = new SelectList(db.CurrentCases, "id", "name");
            ViewBag.doctorId = new SelectList(db.doctors, "id", "name");
            return View();
        }

        //
        // POST: /caseDoctorPrices/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(caseDoctorPrice casedoctorprice)
        {
            if (ModelState.IsValid)
            {
                db.caseDoctorPrices.Add(casedoctorprice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.caseId = new SelectList(db.CurrentCases, "id", "name", casedoctorprice.caseId);
            ViewBag.doctorId = new SelectList(db.doctors, "id", "name", casedoctorprice.doctorId);
            return View(casedoctorprice);
        }

        //
        // GET: /caseDoctorPrices/Edit/5

        public ActionResult Edit(int id = 0)
        {
            caseDoctorPrice casedoctorprice = db.caseDoctorPrices.Find(id);
            if (casedoctorprice == null)
            {
                return HttpNotFound();
            }
            ViewBag.caseId = new SelectList(db.CurrentCases, "id", "name", casedoctorprice.caseId);
            ViewBag.doctorId = new SelectList(db.doctors, "id", "name", casedoctorprice.doctorId);
            return View(casedoctorprice);
        }

        //
        // POST: /caseDoctorPrices/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(caseDoctorPrice casedoctorprice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(casedoctorprice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.caseId = new SelectList(db.CurrentCases, "id", "name", casedoctorprice.caseId);
            ViewBag.doctorId = new SelectList(db.doctors, "id", "name", casedoctorprice.doctorId);
            return View(casedoctorprice);
        }

        //
        // GET: /caseDoctorPrices/Delete/5

        public ActionResult Delete(int id = 0)
        {
            caseDoctorPrice casedoctorprice = db.caseDoctorPrices.Find(id);
            if (casedoctorprice == null)
            {
                return HttpNotFound();
            }
            return View(casedoctorprice);
        }

        //
        // POST: /caseDoctorPrices/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            caseDoctorPrice casedoctorprice = db.caseDoctorPrices.Find(id);
            db.caseDoctorPrices.Remove(casedoctorprice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

teethLab/Views/Doctor/DoctorProfile.cshtml
@model teethLab.doctor
@{
    ViewBag.Title = "DoctorProfile";

}
<style>
        .crossNumberFollow[data-on='false'], .crossNumberFollow[data-on=False], #newMonth[data-on='false'], #newMonth[data-on='False'] {
        margin: 1px;
        position: relative;
        float: left;
        background-color: #012b43;
        color: white;
        height: 23px;
    }

    .crossNumberFollow[data-on='true'], .crossNumberFollow[data-on=True], #newMonth[data-on='true'], #newMonth[data-on='True'] {
        margin: 1px;
        position: relative;
        float: left;
        background-color: red;
        color: white;
        height: 23px;
    }
</style>
<h2>@Model.name</h2>
<div class="row">
    <div class="col-md-6">
        <h2>Imports - Money</h2>
        <table>
            <thead>
                <tr>
                    <th>Value</th>
                    <th>Credit</th>
                    <th>Date</th>
                    <th>Notes</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model.moneys)
                    {
                        <tr>
                            <td>@item.value</td>
                            <td>@item.currentCredit</td>
                            <td>@item.recieveDate</td>
                            <td>@item.notes</td>
                        </tr>

                    }
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h2>Cases</h2>
        <table>
            <thead>
                <tr>
                    <th>Case</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model.caseDoctorPrices)
                    {
                        <tr>
                            <td>@item.CurrentCas.name</td>
                            <td>@item.price</td>
                        </tr>

                    }
                }
            </tbody>
        </table>
        <a href="@Url.Action("Index", "caseDoctorPrices")"><input type="button" value="Prices"/> </a>
    </div>
</div>
<div class="row">
    <h2>Exports - Transactions</h2>
    <table>
        <thead>
            <tr>
            
                <th>Notes</th>
                <th>Deliv. Date</th>
                <th>Patient</th>
                <th>Shade</th>
                <th>Case</th>
                <th>Case No</th>
                <th>Unit Price</th>
                <th>Total Prices</th>
                <th>Print</th>

            
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model.CaseTransactions)
                {
                    <tr>

                        <td>@item.notes</td>
                        @{

                    DateTime toRecDay = (DateTime)item.deliverDate;
                    string date = toRecDay.ToString("yyyy-MM-dd");
                        }
                        <td>@date</td>
                        <td>@item.patientName</td>
                        <td>@item.caseColor1 - @item.caseColor2 -@item.caseColor3</td>
                        @{
                    string caseName = item.CurrentCas.name;
                        }
                        <td>
                            @caseName
                            <div style="position:relative">
                                <div id="" class="colShadeFollow ul" style="float:left">
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UL8" style="float:right">8</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UL7" style="float:right">7</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UL6" style="float:right">6</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UL5" style="float:right">5</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UL4" style="float:right">4</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UL3" style="float:right">3</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UL2" style="float:right">2</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UL1" style="float:right">1</a>

                                </div>

                                <div class="" style="
    position:absolute;

    ">
                                    <img style="width:5px;height:68px;margin:1px 130px" src="~/Content/images/controls/VrLineWhite.png" />
                                </div>

                                <div id="" class="colShadeFollow ur" style="float:right">

                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UR1" style="float:left">1</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UR2" style="float:left">2</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UR3" style="float:left">3</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UR4" style="float:left">4</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UR5" style="float:left">5</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UR6" style="float:left">6</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UR7" style="float:left">7</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.UR8" style="float:left">8</a>


                                </div>

                                <div style="width:100%;">
                                    <img style="width:100%;height:15px;" src="~/Content/images/controls/HorizontalLinewhite.png" />
                                </div>

                                <div id="" class="colShadeFollow ll" style="float:left">
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LL8" style="float:right">8</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LL7" style="float:right">7</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LL6" style="float:right">6</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LL5" style="float:right">5</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LL4" style="float:right">4</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LL3" style="float:right">3</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LL2" style="float:right">2</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LL1" style="float:right">1</a>


                                </div>
                                <div id="" class="colShadeFollow lr" style="float:right">
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LR1" style="float:left">1</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LR2" style="float:left">2</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LR3" style="float:left">3</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LR4" style="float:left">4</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LR5" style="float:left">5</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LR6" style="float:left">6</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LR7" style="float:left">7</a>
                                    <a href="#" class="img-circle crossNumberFollow upper" data-on="@item.LR8" style="float:left">8</a>

                                </div>

                            </div>

                        </td>
                        @{
                    teethLab.teethLabEntities db = new teethLab.teethLabEntities();
                    int caseId = item.CurrentCas.id;
                    int docId = item.doctor.id;

                    teethLab.caseDoctorPrice casePrice = db.caseDoctorPrices.FirstOrDefault(o => o.doctorId == docId && o.caseId == caseId);
                    int price = 0;
                    if (casePrice != null)
                    {
                        price = casePrice.price;
                    }
                    else
                    {
                        price = item.CurrentCas.defaultPrice;
                    }
                        }
                        <td>@item.caseNumber</td>
                        <td>@price</td>
                        <td>@item.price</td>
                        <td>
                            <form method="post" action="@Url.Action("Print", "item")">
                                <input type="hidden" name="transId" value="@item.id" />
                                <input type="submit" value="Print" class="btn btn-primary" />
                            </form>
                        </td>
                    </tr>

                }
            }
        </tbody>
    </table>
</div>

teethLab/Views/Doctor/Index.cshtml
@model IEnumerable<teethLab.doctor>

@{
    ViewBag.Title = "Index";
}


<div data-ng-app="app" data-ng-controller="doctorController" class="row">


    <div class="row">
        <div class="col-md-offset-2 col-md-8" style="text-align:center">
            <p>
                <input type="button" data-ng-hide="addMode" ng-click="enableAddMode()" value="Create New" />
            </p>
            <div data-ng-show="addMode">
                <input type="text" placeholder="Name" data-ng-model="NewModel.name" />
                <input type="text" placeholder="Address" data-ng-model="NewModel.address" />
                <input type="text" placeholder="Phones" data-ng-model="NewModel.phones" />
                <p class="ss-error" ng-bind-html="errorMsg"></p>
                <input type="button" ng-click="addNewModel(NewModel)" value="Add" />
                <input type="button" ng-click="disableAddMode()" value="Cancel" />
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            Name
                        </td>
                        <td>
                            Address
                        </td>
                        <td>
                            Credit
                        </td>
                        <td>
                            Phones
                        </td>
                        <td></td>
                    </tr>
                </thead>

                <tbody>
                    <tr data-ng-repeat="model in models" ng-on-finish-render>
                        <input type="hidden" data-ng-model="model.id" />
                        <input data-ng-hide="true" data-ng-model="model.Credit" />
                        <td>
                            <p data-ng-hide="model.editMode"><a ng-href="@Url.Action("DoctorProfile")/{{model.id}}">{{model.name}}</a></p>
                            <input type="text" data-ng-show="model.editMode" ng-model="model.name" />
                        </td>
                        <td>
                            <p data-ng-hide="model.editMode">{{model.address}}</p>
                            <input type="text" data-ng-show="model.editMode" ng-model="model.address" />
                        </td>
                        <td>
                            <p data-ng-hide="model.editMode">{{model.Credit}}</p>
                        </td>
                        <td>
                            <p data-ng-hide="model.editMode">{{model.phones}}</p>
                            <input type="text" data-ng-show="model.editMode" ng-model="model.phones" />
                        </td>
                        <td>
                            <p data-ng-hide="model.editMode"><input type="button" data-ng-click="toggleEdit(model)" value="Edit" /> | <input type="button" data-ng-click="delete(model)" confirmation-needed="Are You Sure You Want To Delete This ?" value="Delete" /></p>
                            <p data-ng-show="model.editMode"><input type="button" data-ng-click="save(model)" value="Save" /> | <input type="button" data-ng-click="toggleEdit(model)" value="Cancel" /></p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>
    <div class="row">
        <nav class="pagination">
            <span class="page-numbers prev" ng-click="getAllPrev()">Prev</span>
            <a href="javascript:;" data-page="{{n}}" ng-repeat="n in range(minPage,maxPage)" ng-click="getAll(n)" onclick="" class="page-numbers">{{n}}</a>
            <a href="javascript:;" class="page-numbers next" ng-click="getAllNext()">Next</a>
        </nav>
    </div>


    <div data-ng-show="isLoading">
        <img src="~/Content/images/ng-loader.gif" class="ajax-loader" />
    </div>

    @section scripts{
        <script src="~/Scripts/angular.min.js"></script>
        <script src="~/Scripts/AngularCtrs/doctorController.js"></script>
    }
</div>