teethLab/Controllers/CasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace teethLab.Controllers
{
    public class CasesController : Controller
    {
        private teethLabEntities db = new teethLabEntities();

        //
        // GET: /Cases/

        public ActionResult Index()
        {
            return View(db.CurrentCases.ToList());
        }


        public JsonResult all()
        {
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;

            int totalRows, page = 1, size, offset, numOfPages;
            if (Request.Params["page"] != null && Request.Params["page"] != "")
            {
                page = int.Parse(Request.Params["page"]);
            }
            page--;
            size = 5;
            offset = page * size;
            totalRows = db.CurrentCases.Count();
            var models = db.CurrentCases.OrderBy(o => o.id).Skip(offset).Take(size).ToList();
            numOfPages = totalRows / size;
            if (totalRows % size != 0)
            {
                numOfPages++;
            }


            return Json(new { models = models, numOfPages = numOfPages }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Add(CurrentCas model)
        {
            if (ModelState.IsValid)
            {
                db.CurrentCases.Add(model);
                db.SaveChanges();
                return Json(new { success = true, model = model });
            }
            else
            {
                var errors = getErrors(ModelState);
                var res = new { success = false, errors = errors };

                return Json(res);
            }
        }

        private Dictionary<string, List<string>> getErrors(ModelStateDictionary ModelState)
        {
            Dictionary<string, List<string>> errors = new Dictionary<string, List<string>>();
            foreach (var key in ModelState.Keys)
            {
                if (ModelState[key].Errors.Count > 0)
                {
                    List<string> keyErrors = new List<string>();
                    foreach (var error in ModelState[key].Errors)
                    {
                        keyErrors.Add(error.ErrorMessage);
                    }
                    errors.Add(key, keyErrors);
                }
            }
            return errors;
        }


        [HttpPost]
        public JsonResult Edit(CurrentCas model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            else
            {
                var errors = getErrors(ModelState);
                var res = new { success = false, errors = errors };

                return Json(res);
            }
        }
        [HttpPost]
        public JsonResult Delete(CurrentCas model)
        {
            CurrentCas obj = db.CurrentCases.Find(model.id);
            db.CurrentCases.Remove(obj);
            db.SaveChanges();
            return Json(new { success = true });
        }


        ////
        //// GET: /Cases/Create

        //public ActionResult Create()
        //{
        //    return View();
        //}

        ////
        //// POST: /Cases/Create

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(CurrentCas currentcas)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.CurrentCases.Add(currentcas);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(currentcas);
        //}

        ////
        //// GET: /Cases/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    CurrentCas currentcas = db.CurrentCases.Find(id);
        //    if (currentcas == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(currentcas);
        //}

        ////
        //// POST: /Cases/Edit/5

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(CurrentCas currentcas)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(currentcas).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(currentcas);
        //}

        ////
        //// GET: /Cases/Delete/5

        //public ActionResult Delete(int id = 0)
        //{
        //    CurrentCas currentcas = db.CurrentCases.Find(id);
        //    if (currentcas == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(currentcas);
        //}

        ////
        //// POST: /Cases/Delete/5

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    CurrentCas currentcas = db.CurrentCases.Find(id);
        //    db.CurrentCases.Remove(currentcas);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

teethLab/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace teethLab.Controllers
{
    public class ProductsController : Controller
    {
        private teethLabEntities db = new teethLabEntities();

        //
        // GET: /Products/

        public ActionResult Index()
        {
            return View(db.products.ToList());
        }

        public JsonResult all()
        {
            db.Configuration.ProxyCreationEnabled = false;

            int totalRows, page = 1, size, offset, numOfPages;
            if (Request.Params["page"] != null && Request.Params["page"] != "")
            {
                page = int.Parse(Request.Params["page"]);
            }
            page--;
            size = 5;
            offset = page * size;
            totalRows = db.products.Count();
            var models = db.products.OrderBy(o => o.id).Skip(offset).Take(size).ToList();
            numOfPages = totalRows / size;
            if (totalRows % size != 0)
            {
                numOfPages++;
            }
            return Json(new { models = models, numOfPages = numOfPages }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Add(product model)
        {
            model.enterDate = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.products.Add(model);
                db.SaveChanges();
                return Json(new { success = true, model = model });
            }
            return Json(new { success = false });

        }


        [HttpPost]
        public JsonResult Edit(product model)
        {
            if (ModelState.IsValid)
            {    
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        [HttpPost]
        public JsonResult Delete(product model)
        {
            product obj = db.products.Find(model.id);
            db.products.Remove(obj);
            db.SaveChanges();
            return Json(new { success = true });
        }

        public ActionResult ProductProfile(int id)
        {
            product pro = db.products.FirstOrDefault(o => o.id == id);
            if (pro != null)
            {
                return View(pro);
            }
            return HttpNotFound();
        }
        //
        


        //public void addNewUnit()
        //{
        //    string newUnit = Request["newUnit"];
        //    if (newUnit != null && newUnit != string.Empty)
        //    {
        //        db = new teethLabEntities();
        //        if (db.Units.Where(o => o.unit1.ToLower() == newUnit.ToLower()).Count() == 0)
        //        {
        //            Unit unit = new Unit { unit1 = newUnit };
        //            db.Units.Add(unit);
        //            db.SaveChanges();
        //            Response.Write("success,"+unit.id);
        //        }
        //    }
        //}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

teethLab/Controllers/UnitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace teethLab.Controllers
{
    public class UnitsController : Controller
    {
        private teethLabEntities db = new teethLabEntities();

        //
        // GET: /Units/

        public ActionResult Index()
        {
            return View(db.Units.ToList());
        }
        public JsonResult all()
        {
            db.Configuration.ProxyCreationEnabled = false;

            int totalRows, page = 1, size, offset, numOfPages;
            if (Request.Params["page"] != null && Request.Params["page"] != "")
            {
                page = int.Parse(Request.Params["page"]);
            }
            page--;
            size = 5;
            offset = page * size;
            totalRows = db.Units.Count();
            var units = db.Units.OrderBy(o => o.id).Skip(offset).Take(size).ToList();
            numOfPages = totalRows / size;
            if (totalRows % size != 0)
            {
                numOfPages++;
            }
            return Json(new { models = units, numOfPages = numOfPages }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Add(Unit model)
        {
            if (ModelState.IsValid)
            {
                db.Units.Add(model);
                db.SaveChanges();
                return Json(new { success = true, model = model });
            }
            else
            {
                var errors = getErrors(ModelState);
                var res = new { success = false, errors = errors };

                return Json(res);
            }
        }

        private Dictionary<string, List<string>> getErrors(ModelStateDictionary ModelState)
        {
            Dictionary<string, List<string>> errors = new Dictionary<string, List<string>>();
            foreach (var key in ModelState.Keys)
            {
                if (ModelState[key].Errors.Count > 0)
                {
                    List<string> keyErrors = new List<string>();
                    foreach (var error in ModelState[key].Errors)
                    {
                        keyErrors.Add(error.ErrorMessage);
                    }
                    errors.Add(key, keyErrors);
                }
            }
            return errors;
        }


        [HttpPost]
        public JsonResult Edit(Unit model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            else
            {
                var errors = getErrors(ModelState);
                var res = new { success = false, errors = errors };

                return Json(res);
            }
        }
        [HttpPost]
        public JsonResult Delete(Unit model)
        {
            Unit unit = db.Units.Find(model.id);
            db.Units.Remove(unit);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

teethLab/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace teethLab.Controllers
{
    public class UserController : Controller
    {
        private teethLabEntities db = new teethLabEntities();

        //
        // GET: /User/

        public ActionResult Index()
        {
            return View(db.users.ToList());
        }

        //
        // GET: /User/Details/5

        public ActionResult Details(int id = 0)
        {
            user user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // GET: /User/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /User/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(user user)
        {
            if (ModelState.IsValid)
            {
                db.users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        //
        // GET: /User/Edit/5

        public ActionResult Edit(int id = 0)
        {
            user user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(user user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        //
        // GET: /User/Delete/5

        public ActionResult Delete(int id = 0)
        {
            user user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            user user = db.users.Find(id);
            db.users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        public ActionResult viewRegister()
        {
            if (!tools.isAdminLogged())
            {
                return Redirect(Url.Action("viewLogin", "user"));
            }

            ViewData["error"] = TempData["error"];
            return View();
        }
        //view login
        public ActionResult viewLogin()
        {

            ViewData["error"] = TempData["error"];
            return View();
        }
        public ActionResult logOut()
        {
            Session["userId"] = 0;
            return Redirect(Url.Action("Index", "Home"));
        }
        public ActionResult login()
        {

            string name = Request.Form["name"];
            string password = Request.Form["password"];
            teethLabEntities db = new teethLabEntities();
            if (db.users.Where(u => u.name == name && u.password == password).Count() > 0)
            {
                user user = db.users.Where(u => u.name == name && u.password == password).First();
                Session.Add("userId", user.id);
                return Redirect(Url.Action("Index", "Home"));
            }

            return RedirectToAction("viewLogin", new { error = "الاسم او الرقم السري غير صحيح" });
        }
        public ActionResult register()
        {
            string name = Request.Form["name"];
            string password = Request.Form["password"];
            string passwordConfirm = Request.Form["confirmPassword"];
            teethLabEntities db = new teethLabEntities();
            if (db.users.Where(o => o.name == name).Count() > 0)
            {

                TempData["error"] = "الاسم موجود مسبقآ , رجاء اختيار اسم اخر";

                return Redirect(Url.Action("viewRegister", "user"));
            }
            if (password != passwordConfirm)
            {
                TempData["error"] = "الرقم السري غير مطابق";
                return Redirect(Url.Action("viewRegister", "user"));
            }

            user user = new user();
            user.name = name;
            user.password = password;
            db.users.Add(user);
            db.SaveChanges();
            TempData["error"] = "تمت الاضافه بنجاح";
            return Redirect(Url.Action("viewRegister", "user"));
        }
    }
}

teethLab/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    string day = (string)ViewData["day"];
}

@*<h2>Index</h2>

<div>
    <div class="row">
        <form class="form-inline" method="post" action="@Url.Action("storenewdate" , "Home")">
            <div class="form-group">
                <div class="col-md-3">
                    <label>Select Date : </label>
                </div>
                <div class="col-md-6">
                    <input type="date" value="@day" class="form-control" name="date" id="date" />
                </div>
                <div class="col-md-3">
                    <input type="submit" name="submit" value="submit" id="submit" class="form-control" />
                </div>
            </div>
        </form>
    </div>
</div>*@

<section id="bricks">

    <div class="row masonry">

        <!-- brick-wrapper -->
        <div class="bricks-wrapper">

            <div class="grid-sizer"></div>
            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">Input Case</a>
                                <a href="#">Output Case</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("followUpCases", "Transaction")">Cases</a></h1>

                    </div>
                    <div class="entry-excerpt">
                        this is the most important page , any inputs and outputs for cases goes here
                    </div>
                </div>

            </article>
            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">Imports</a>
                                <a href="#">Exports</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("viewMoneyDays", "Money")">Financies</a></h1>

                    </div>
                    <div class="entry-excerpt">
                        all money transactions goes here
                    </div>
                </div>

            </article>


            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">cases</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("Index", "Cases")">Current Cases</a></h1>

                    </div>
                    <div class="entry-excerpt">
all cases that our lab treat with , goes here !                    </div>
                </div>

            </article>
            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">employees</a>
                                <a href="#">small payroll</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("Index", "Employee")">Employees</a></h1>

                    </div>
                    <div class="entry-excerpt">
salaries and any data about employees goes here !                    </div>
                </div>

            </article>
            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">supplier</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("Index", "Companies")">Suppliers</a></h1>

                    </div>
                    <div class="entry-excerpt">
suppliers and there materials goes here                    </div>
                </div>

            </article>
            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">doctors</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("Index", "Doctor")">Doctors</a></h1>

                    </div>
                    <div class="entry-excerpt">
                        cases and money for all doctors goes here
                    </div>
                </div>

            </article>

            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">Products</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("Index", "Products")">Materials</a></h1>

                    </div>
                    <div class="entry-excerpt">
all materials goes here                    </div>
                </div>

            </article>

            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">Supplier</a>
                                <a href="#">Products</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("Index", "CompanyProducts")">Supplier Products</a></h1>

                    </div>
                    <div class="entry-excerpt">
                        Supplier products transactions goes here
                    </div>
                </div>

            </article>

            <article class="brick entry format-standard animate-this">

                <div class="entry-text">
                    <div class="entry-header">

                        <div class="entry-meta">
                            <span class="cat-links">
                                <a href="#">Product</a>
                                <a href="#">Units</a>
                            </span>
                        </div>

                        <h1 class="entry-title"><a href="@Url.Action("Index", "Units")">Units</a></h1>

                    </div>
                    <div class="entry-excerpt">
                        Units of all products goes here
                    </div>
                </div>

            </article>

        </div>
    </div>

</section>

@*<li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li><a href="@Url.Action("Index", "User")">Users</a></li>
*@